# Numpy: Numeric computing library

Numpy(numerical Python) is one of the core packages for numerical computing in python
Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on Numpy

In [16]:
import numpy as np

## Creating Numpy Arrays from Python Lists

Unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point)

In [22]:
# list in python: cho phép chứa các item có khác kiểu dl
[3.14, 4, 2, 3] 

[3.14, 4, 2, 3]

In [23]:
# numpy array cụ thể hóa kiểu dl của mảng
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [24]:
# numpy conver all int -> float
np. array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

Unlike Python lists, NumPy arrays can explicitly be multi-dimensional

In [25]:
#nested lists result in multi-dimensional arrays
x = np.array([range(i, i+3) for i in [2, 4, 6]])
x

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [26]:
a1 = np.array([1, 2, 3, 4])

In [27]:
type(a1)

numpy.ndarray

In [28]:
a1.dtype

dtype('int32')

In [29]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

In [30]:
type(a2)

numpy.ndarray

In [31]:
# return kiểu dl trong matrix
a2.dtype 

dtype('int32')

### NumPy Array Attributes

In [32]:
# return kich thuc matrix (row, column)
a2.shape 

(2, 3)

In [33]:
# return số chiều của mảng
a2.ndim

2

In [34]:
# return: number of elements 
a2.size 

6

In [35]:
len(a2)

2

In [36]:
a2.itemsize

4

In [37]:
a2.dtype

dtype('int32')

In [38]:
A = np.array([[1, 2, 3], [2, 3, 4], [5, 6, 2]])

In [40]:
A

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 2]])

In [42]:
A.itemsize

4

In [58]:
a = np.arange(10) # create a matrix
b = np.arange(2, 100, 2)
c = np.linspace(3, 100, 3)

### BT

In [64]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [71]:
n = int(input('n = '))
a1 = np.linspace(1, 10, n)
a1

n = 7


array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [67]:
a2 = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 1],
               [3, 4, 2, 5, 2]])
a2

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [3, 4, 2, 5, 2]])

In [68]:
a2.ndim

2

In [78]:
a2.shape

(3, 5)

In [73]:
a2.dtype

dtype('int32')

In [79]:
n = int(input('n = '))
m = int(input('m = '))
a3 = np.eye(n*n)
a3

n = 3
m = 1


array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [86]:
a4 = np.diag(a)
a4

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])