# Creating Numpy Arrays from Scratch

### zeros, ones, full, arange, linspace, eye, diag


In [2]:
import numpy as np

In [3]:
# shift + tab : để được đối số truyền vào

#### Zeros: create an array filled 0

In [4]:
np.zeros(10, dtype = int) # truyền 1 đối số là mảng 1 chiều có 10 phần tử

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.zeros(10) # mặc định dtype = float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# Create a 3x5 floating-point array filled with zeros
np.zeros((3, 5), dtype = int)  #multi-dimensional

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
Create a 3x5 floating-point array filled with zeros
np.zeros((3, 5))

SyntaxError: invalid syntax (1864103116.py, line 1)

#### Ones: create an array filled 1

In [ ]:
np.ones(10)

In [ ]:
np.ones((3, 5))

#### Full: fill value

In [ ]:
# create an 2*4 array filled with 4
np.full([2,4], 4)

In [ ]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

#### Arange: Create an array filled with a linear sequence

In [ ]:
# create an array filled with a linear sequence
# starting at 0; ending at a number, stepping by 1(mac dinh)
#(this is similar to the built-in range() function)
np.arange(0, 20, 2)

In [ ]:
# create an array of five values evenly space between 0 and 1
np.linspace(0, 1, 5) # chia đều thành các phần trong khoảng [0, 1]

#### eys: ma trận đơn vị

In [10]:
a = np.eye(3)

In [11]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])