# random

In [3]:
import numpy as np

#### random: create an array with elements ngẫu nhiên 

In [4]:
# seed for reproducibility
np.random.seed(0)
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1

np.random.random((3,3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [5]:
np.random.random(5)

array([0.38344152, 0.79172504, 0.52889492, 0.56804456, 0.92559664])

In [6]:
# rand(d0, d1, ..., dn)
# Random values in a given shape
np.random.rand(3, 4)

array([[0.07103606, 0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834, 0.79915856],
       [0.46147936, 0.78052918, 0.11827443, 0.63992102]])

In [18]:
np.random.randn(2, 3) # theo gauss

array([[-0.68481009, -0.87079715, -0.57884966],
       [-0.31155253,  0.05616534, -1.16514984]])

In [7]:
# randint(low, high=None, size=None, dtype=int)
# Return random integers from 'low' (inclusive) to 'high' (exclusive).
np.random.randint(10, 15, size = 5) 

array([11, 11, 10, 12, 14])

In [8]:
# Độ lệch chuẩn
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(2, 3, (3, 3))

array([[-2.06714117,  1.6576924 , -0.53269259],
       [ 4.11692243,  0.80364148, -0.4815896 ],
       [ 0.7527659 ,  0.42646342,  4.43930382]])

In [9]:
# not include 50
# randint(low, high=None, size=None, dtype=int)
# Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(20, 50, (2, 4))

array([[30, 46, 44, 21],
       [21, 27, 29, 45]])

In [17]:
a = np.random.randn(2, 4)
a

array([[ 0.46278226, -0.90729836,  0.0519454 ,  0.72909056],
       [ 0.12898291,  1.13940068, -1.23482582,  0.40234164]])

#### eye, empty

In [11]:
# ma trận đơn vị
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.eye(3, dtype='int8')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [13]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([3.33774490e-307, 2.55896905e-307, 5.11793131e-307])