# Array indexing & Slicing

## one-dimensional subarray

In [2]:
import numpy as np

In [3]:
x1 = np.random.randint(0, 20, size = 6) # One-dimensional array

In [4]:
x1

array([16, 11,  3,  7, 16,  0])

In [5]:
print(x1[4]) #access index 4
print(x1[-1]) # position end

16
0


## multi-dimensional subarray

In [6]:
x2 = np.random.randint(0, 10, (3, 4)) # Two-dimensional array

In [7]:
x2

array([[4, 5, 0, 9],
       [1, 1, 2, 7],
       [7, 2, 6, 3]])

In [8]:
x2[1, 2] # access row 1 and column 2

2

In [9]:
x2[1, 2] = 8 # change 

In [10]:
x2


array([[4, 5, 0, 9],
       [1, 1, 8, 7],
       [7, 2, 6, 3]])

In [11]:
x2[:2, :3]  # two rows, three columns

array([[4, 5, 0],
       [1, 1, 8]])

In [12]:
print(x2[:, 0])  # first column of x2

[4 1 7]


In [13]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
x = np.array([1, 2, 3])

In [15]:
# column vector via reshape 
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

## Slicing

## x[start:stop:step]

In [16]:
x1

array([16, 11,  3,  7, 16,  0])

In [17]:
x1[:3] # First 3 Element

array([16, 11,  3])

In [18]:
x1[2:4] # middle sub-array

array([3, 7])

In [19]:
# every other element, every 2 step
x1[::2]

array([16,  3, 16])

In [30]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])

a[:, 3:]
a[:, -3]
a[0:2, 2]
a[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])