# Reshaping of Array and Transpose

## reshaping

In [2]:
import numpy as np

In [4]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
grid = np.arange(1, 10)
grid.shape[0]

9

In [8]:
grid.reshape([3, 3]) # tạo thành ma trận 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
x = np.array([[1, 2, 3],
            [4, 5, 6]])
#x.shape # return : kích thước của mảng

#x.shape[0] #return : kích thước của row
x.shape[1] #return : kích thước của column


3

In [11]:
x.reshape([1, 3]).shape

(1, 3)

## Transpose

In [16]:
x = np.array([[1., 2.], [3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [15]:
# ma trận chuyển vị
x.T

array([[1., 3.],
       [2., 4.]])

In [17]:
x1 = np.array([1, 2, 3, 4, 5])
x1.shape

(5,)