# Array Concatenation and Splitting

## Concatenation

In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [4]:
np.concatenate((x, y))

array([1, 2, 3, 3, 2, 1])

In [5]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# concatenate along the first axis
np.concatenate([grid, grid]) # axis = 0 by default

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [6]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [7]:
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

x = np.array([1, 2, 3])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [8]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Splitting of arrays

In [9]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [10]:
grid = np.arange(16).reshape((4, 4))
grids

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])