# Sort

In [4]:
import numpy as np

In [6]:
x = np.array([2, 1, 4, 3, 5])

In [7]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [9]:
np.argsort(x) # return index of value

array([1, 0, 3, 2, 4], dtype=int64)

## sorting along rows or columns

In [11]:
np.random.seed(42)

In [13]:
MatA = np.random.randint(0, 10, size=(4, 6))

In [14]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [15]:
np.sort(MatA, axis = 0) # colummn = 0

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [16]:
np.sort(MatA, axis = 1) # row = 1

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])