# Linear Algebra

In [3]:
import numpy as np

In [4]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

In [5]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]])

In [6]:
A.dot(B) # nhân tích vô hướng

array([[20, 14],
       [56, 41],
       [92, 68]])

In [7]:
A @ B # nhân tích vô hướng

array([[20, 14],
       [56, 41],
       [92, 68]])

In [8]:
B.T @ A 

array([[36, 48, 60],
       [24, 33, 42]])

# Dot Product example

In [11]:
# number of  jars sold
np.random.seed(0)
sales_amounts =  np.random.randint(20, size=(5, 3))

In [12]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [14]:
# Create weekly_sales DataFrame

import pandas as pd

weekly_sales = pd.DataFrame(sales_amounts, index = ['Mon', "Tues", "Wed", "Thurs", "Fri"],
                           columns = ['Almond Butter', 'Peanut Butter', 'Cashew Butter'])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [15]:
# Create a price array
prices = np.array([10, 8, 12])
prices.shape

(3,)

In [19]:
butter_prices = pd.DataFrame(prices.reshape(1, 3), index = ["Price"], columns = ['Almond Butter', 'Peanut Butter', 'Cashew Butter'])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [24]:
total_price = weekly_sales.shape, butter_prices.shape
total_price

((5, 3), (1, 3))

In [23]:
weekly_sales.dot(butter_prices.T)

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [26]:
weekly_saleS["Total Price"] = total_price

NameError: name 'weekly_saleS' is not defined