# Numpy: Numeric computing library

numpy(numerical Python) is one of the core packages for 
numerical computing in python

Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on Numpy

In [3]:
import numpy as np


## Creating Numpy Arrays from Python Lists

In [4]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
[3.14, 4, 2, 3] # list in python: cho phép chưa các item khác kiểu dl

[3.14, 4, 2, 3]

In [6]:
 np. array([3.14, 4, 2, 3]) # numpy conver all int -> float

array([3.14, 4.  , 2.  , 3.  ])

In [7]:
# numpy array cụ thể hóa kiểu dl của mảng
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [8]:
a1 = np.array([1, 2, 3, 4])

In [9]:
type(a1)

numpy.ndarray

In [11]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])

In [12]:
type(a2)

numpy.ndarray

In [15]:
a2.shape # return kich thuc matrix (row, column)

(2, 3)

In [16]:
a2.ndim # return số chiều của mảng

2

In [17]:
a2.dtype # return kiểu dl trong matrix

dtype('int32')

In [18]:
a2.size # return: number of elements 

6