# Numpy: Numeric computing library

Numpy(numerical Python) is one of the core packages for numerical computing in python
Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on Numpy

In [16]:
import numpy as np

## Creating Numpy Arrays from Python Lists

In [17]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

Unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point)

In [18]:
# list in python: cho phép chứa các item có khác kiểu dl
[3.14, 4, 2, 3] 

[3.14, 4, 2, 3]

In [19]:
# numpy array cụ thể hóa kiểu dl của mảng
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [20]:
# numpy conver all int -> float
np. array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

Unlike Python lists, NumPy arrays can explicitly be multi-dimensional

In [21]:
#nested lists result in multi-dimensional arrays
x = np.array([range(i, i+3) for i in [2, 4, 6]])
x

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [22]:
a1 = np.array([1, 2, 3, 4])

In [23]:
type(a1)

numpy.ndarray

In [24]:
a1.dtype

dtype('int32')

In [14]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

In [12]:
type(a2)

numpy.ndarray

In [17]:
# return kiểu dl trong matrix
a2.dtype 

dtype('int32')

### NumPy Array Attributes

In [15]:
# return kich thuc matrix (row, column)
a2.shape 

(2, 3)

In [16]:
# return số chiều của mảng
a2.ndim

2

In [25]:
# return: number of elements 
a2.size 

6