# Creating Numpy Arrays from Scratch

### zeros, ones, full, arange, linspace

In [9]:
import numpy as np

In [3]:
# shift + tab : để được đối số truyền vào

#### Zeros: create an array filled 0

In [11]:
np.zeros(10, dtype = int) # truyền 1 đối số là mảng 1 chiều có 10 phần tử

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros(10) # mặc định dtype = float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
# Create a 3x5 floating-point array filled with zeros
np.zeros((3, 5), dtype = int)  #multi-dimensional

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
Create a 3x5 floating-point array filled with zeros
np.zeros((3, 5))

#### Ones: create an array filled 1

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### Full: fill value

In [23]:
# create an 2*4 array filled with 4
np.full([2,4], 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [24]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

#### Arange: Create an array filled with a linear sequence

In [25]:
# create an array filled with a linear sequence
# starting at 0; ending at a number, stepping by 1(mac dinh)
#(this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
# create an array of five values evenly space between 0 and 1
np.linspace(0, 1, 5) # chia đều thành các phần trong khoảng [0, 1]

array([0.  , 0.25, 0.5 , 0.75, 1.  ])