# creating Numpy Arrays from Csratch

### zeros, ones, full, arange, linspace

In [2]:
import numpy as np

In [3]:
# shift + tab 

In [8]:
# create an array fill 0
# dtype = int: 
np.zeros([2, 4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
np.zeros([2, 4]) # mặc định = float

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# create an array fill 1
np.ones([3, 5], dtype = 'float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# create an array filled with a linear sequence
# starting at 0; ending at a number, stepping by 1(mac dinh)
#(this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# create an array filled with ý muốn
np.full([2,4], 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [21]:
# create an array of five values evenly space between 0 and 1
np.linspace(0, 1, 5) # chia đều thành các phần trong khoảng [0, 1]

array([0.  , 0.25, 0.5 , 0.75, 1.  ])