In [1]:
import numpy as np

# random

In [3]:
# create an array with elements ngẫu nhiên 

In [11]:
# seed for reproducibility
np.random.seed(0)
np.random.random((4, 4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [19]:
np.random.random((4, 4))

array([[0.4686512 , 0.97676109, 0.60484552, 0.73926358],
       [0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949, 0.52324805]])

In [21]:
np.random.rand(4,4)

array([[0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402]])

In [15]:
# do lech chuyan = 1
# min = 0

np.random.normal(0, 1, [3, 3]) 

array([[-1.70627019,  1.9507754 , -0.50965218],
       [-0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656]])

In [18]:
# not include 50
np.random.randint(20, 50, [3, 4])

array([[29, 23, 20, 25],
       [20, 37, 38, 24],
       [22, 36, 49, 23]])