# random

In [1]:
import numpy as np

#### random: create an array with elements ngẫu nhiên 

In [6]:
# seed for reproducibility
np.random.seed(0)
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1

np.random.random((3,3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [17]:
np.random.random(5)

array([0.10022689, 0.91948261, 0.7142413 , 0.99884701, 0.1494483 ])

In [21]:
# rand(d0, d1, ..., dn)
# Random values in a given shape.
np.random.rand(3, 4)

array([[0.311945  , 0.39822106, 0.20984375, 0.18619301],
       [0.94437239, 0.7395508 , 0.49045881, 0.22741463],
       [0.25435648, 0.05802916, 0.43441663, 0.31179588]])

In [23]:
# randint(low, high=None, size=None, dtype=int)
# Return random integers from 'low' (inclusive) to 'high' (exclusive).
np.random.randint(10, 15, size = 5) 

array([11, 11, 12, 10, 13])

In [25]:
# Độ lệch chuẩn
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(2, 3, (3, 3))

array([[ 4.76257647,  2.95618296,  4.57049184],
       [ 0.04692322, -1.10272853,  4.04478355],
       [-0.41022899, -0.06864933,  0.63340249]])

In [26]:
# not include 50
# randint(low, high=None, size=None, dtype=int)
# Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(20, 50, (2, 4))

array([[39, 27, 28, 49],
       [33, 25, 20, 28]])

#### eye, empty

In [28]:
# ma trận đơn vị
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.eye(3, dtype='int8')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [32]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])