# Array indexing & Slicing

## one-dimensional subarray

In [21]:
import numpy as np

In [4]:
x1 = np.random.randint(0, 20, size = 6)

In [5]:
x1

array([15,  1, 17,  9,  5, 18])

In [6]:
x1[4] #access index 4

5

In [7]:
x1[0]

15

In [8]:
x1[-1] # position end

18

## multi-dimensional subarray

In [11]:
x2 = np.random.randint(0, 10, [3,4])

In [12]:
x2

array([[0, 4, 6, 2],
       [6, 5, 6, 4],
       [8, 6, 1, 7]])

In [13]:
x2[1, 2] # access

6

In [14]:
x2[1, 2] = 8 # change 

In [15]:
x2


array([[0, 4, 6, 2],
       [6, 5, 8, 4],
       [8, 6, 1, 7]])

## Slicing

## x[start:stop:step]

In [1]:
x1

NameError: name 'x1' is not defined

In [22]:
x1[:3] # start: mặc định = 0

NameError: name 'x1' is not defined

In [23]:
x1[2:4]

NameError: name 'x1' is not defined

In [17]:
# every other element, every 2 step
x1[::2]

NameError: name 'x1' is not defined

## Reshaping of Arrays & Transpose

In [20]:
grid = np.arange(1, 10)

NameError: name 'np' is not defined