# Array indexing & Slicing

## one-dimensional subarray

In [2]:
import numpy as np

In [3]:
x1 = np.random.randint(0, 20, size = 6) # One-dimensional array

In [4]:
x1

array([7, 7, 5, 4, 8, 7])

In [7]:
print(x1[4]) #access index 4
print(x1[-1]) # position end

8
7


## multi-dimensional subarray

In [11]:
x2 = np.random.randint(0, 10, (3, 4)) # Two-dimensional array

In [12]:
x2

array([[9, 7, 8, 5],
       [8, 5, 0, 6],
       [4, 3, 4, 4]])

In [13]:
x2[1, 2] # access row 1 and column 2

0

In [14]:
x2[1, 2] = 8 # change 

In [15]:
x2


array([[9, 7, 8, 5],
       [8, 5, 8, 6],
       [4, 3, 4, 4]])

In [22]:
x2[:2, :3]  # two rows, three columns

array([[9, 7, 8],
       [8, 5, 8]])

In [25]:
print(x2[:, 0])  # first column of x2

[9 8 4]


In [26]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x = np.array([1, 2, 3])

In [ ]:
# column vector via reshape 
x.reshape((3, 1))

## Slicing

## x[start:stop:step]

In [16]:
x1

array([7, 7, 5, 4, 8, 7])

In [17]:
x1[:3] # First 3 Element

array([7, 7, 5])

In [18]:
x1[2:4] # middle sub-array

array([5, 4])

In [19]:
# every other element, every 2 step
x1[::2]

array([7, 5, 8])