# Reshaping of Array and Transpose

## reshaping

In [2]:
import numpy as np

In [5]:
grid = np.arange(1, 10)
grid.shape

(9,)

In [6]:
grid.reshape([3,3]) # tạo thành ma trận 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
x = np.array([1, 2, 3])
x.shape # kích thước của mảng

(3,)

In [11]:
x.reshape([1, 3]).shape

(1, 3)

## Transpose

In [16]:
x = np.array([[1., 2.], [3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [15]:
# ma trận chuyển vị
x.T

array([[1., 3.],
       [2., 4.]])