# Array Concatenation and Splitting

In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [4]:
np.concatenate ([x, y])

array([1, 2, 3, 3, 2, 1])

In [5]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.concatenate([grid, grid]) # axis = 0 by default

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [6]:
np.concatenate([grid, grid], axis =1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])