# Summary statistics

In [2]:
import numpy as np

In [11]:
a = np.array([600, 470, 170, 430, 300])

In [12]:
a.sum()

1970

In [13]:
a.mean() # mean : giá trị trung bình

394.0

In [16]:
a.var() # var: phương sai

21704.0

In [17]:
a.std() # std: độ lệch chuẩn

147.32277488562318

In [18]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

In [19]:
A.sum()

45

In [20]:
A.mean()

5.0

In [23]:
A.std()

2.581988897471611

In [22]:
A.mean(axis = 1)

array([2., 5., 8.])

In [25]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [24]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])