In [1]:
import numpy as np

In [2]:
a = np.arange(3)

In [3]:
a

array([0, 1, 2])

In [4]:
a+5

array([5, 6, 7])

In [6]:
a-5

array([-5, -4, -3])

In [8]:
a*5

array([ 0,  5, 10])

In [24]:
a = np.ones((3,3))
b = np.arange(3).reshape(3, 1)

In [25]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
b

array([[0],
       [1],
       [2]])

In [27]:
a.shape

(3, 3)

In [28]:
a+b

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])